// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------- //
// hub75_shift //
// ----------- //

#define hub75_shift_wrap_target 0
#define hub75_shift_wrap 2
#define hub75_shift_pio_version 0

static const uint16_t hub75_shift_program_instructions[] = {
            //     .wrap_target
    0x6006, //  0: out    pins, 6         side 0
    0xb042, //  1: nop                    side 1
    0xa042, //  2: nop                    side 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program hub75_shift_program = {
    .instructions = hub75_shift_program_instructions,
    .length = 3,
    .origin = -1,
    .pio_version = hub75_shift_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config hub75_shift_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + hub75_shift_wrap_target, offset + hub75_shift_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

